%=========================================================================
% Função para o cálculo das funções base
%=========================================================================

function [Phi, GradPhi, Qui] = BasisFunc(NCSI, NETA)

    % Para os pontos de Gauss:
    % NCSI na direção horizontal
    % NETA na direção vertical
    
    % Vetor Phi (9 linhas e 1 coluna)
    Phi = [ ((NCSI)*(NCSI - 1)*(NETA)*(NETA - 1))/4;...
            ((NCSI)*(NCSI + 1)*(NETA)*(NETA - 1))/4;...
            ((NCSI)*(NCSI + 1)*(NETA)*(NETA + 1))/4;...
            ((NCSI)*(NCSI - 1)*(NETA)*(NETA + 1))/4;...
            ((NCSI - 1)*(NCSI + 1)*(NETA)*(NETA - 1))/(-2);...
            ((NCSI)*(NCSI + 1)*(NETA-1)*(NETA + 1))/(-2);...
            ((NCSI + 1)*(NCSI - 1)*(NETA)*(NETA + 1))/(-2);...
            ((NCSI)*(NCSI - 1)*(NETA + 1)*(NETA - 1))/(-2);...
            ((NCSI + 1)*(NCSI - 1)*(NETA - 1)*(NETA + 1)) ];
       
    % Matriz GradPhi (9 colunas e 2 linhas)
    GradPhi = [ ((2*NCSI - 1)*((NETA)^2 - NETA))/4 ...
                ((2*NCSI + 1)*((NETA)^2 - NETA))/4 ...
                ((2*NCSI + 1)*((NETA)^2 + NETA))/4 ...
                ((2*NCSI - 1)*((NETA)^2 + NETA))/4 ... 
                ((2*NCSI)*((NETA)^2 - NETA))/(-2) ...
                ((2*NCSI + 1)*((NETA)^2 - 1))/(-2) ... 
                ((2*NCSI)*((NETA)^2 + NETA))/(-2) ...
                ((2*NCSI - 1)*((NETA)^2 - 1))/(-2) ... 
                ((2*NCSI)*((NETA)^2 - 1));...
                
                (((NCSI)^2 - NCSI)*(2*NETA - 1))/4 ...
                ((NCSI)^2 + NCSI)*(2*NETA - 1)/4 ... 
                ((NCSI)^2 + NCSI)*(2*NETA + 1)/4 ... 
                ((NCSI)^2 - NCSI)*(2*NETA + 1)/4 ... 
                ((NCSI)^2 - 1)*(2*NETA - 1)/(-2) ...
                ((NCSI)^2 + NCSI)*(2*NETA)/(-2) ... 
                ((NCSI)^2 - 1)*(2*NETA + 1)/(-2) ...
                ((NCSI)^2 - NCSI)*(2*NETA)/(-2) ...
                ((NCSI)^2 - 1)*(2*NETA) ];

    % Vetor Qui (3 linhas e 1 coluna)
    Qui = [1; NETA; NCSI];

end
